# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os:
  - linux
  - osx

cache: packages
before_install:
      - brew update
      - brew cask reinstall xquartz
      - brew install tcl-tk
      - R -e 'source("https://install-github.me/r-lib/remotes")'
addons:
   apt:
     packages:
       - pandoc
       - libgsl0-dev
       - libxml2-dev

script:
   - R CMD build . --compact-vignettes=gs+qpdf
   - xvfb-run R CMD check *tar.gz --as-cran

