# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

addons:
   apt:
     packages:
       - pandoc
       - libgsl0-dev
       - libxml2-dev

script:
   - R CMD build . --compact-vignettes=gs+qpdf
   - xvfb-run R CMD check *tar.gz --as-cran

